# Generated by Django 4.0.3 on 2025-02-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pod',
            name='status',
            field=models.CharField(choices=[('Alive', 'Alive'), ('Affected', 'Affected'), ('Dead', 'Dead')], default='Alive', max_length=10),
        ),
    ]
