# Generated by Django 3.2.16 on 2025-02-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_pod_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('reply', models.TextField()),
            ],
        ),
    ]
