apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-chart-agent
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: agent
  template:
    metadata:
      labels:
        app: agent
    spec:
      containers:
        - name: agent
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          ports:
            - containerPort: {{ .Values.service.containerPort }}
              name: container-http
          env:
          - name: OPENAI_API_KEY
            valueFrom:
              secretKeyRef:
                name: agent-secrets
                key: OPENAI_API_KEY
          - name: OPENAI_PROJECT_ID
            valueFrom:
              secretKeyRef:
                name: agent-secrets
                key: OPENAI_PROJECT_ID
          - name: OPENAI_ORG_ID
            valueFrom:
              secretKeyRef:
                name: agent-secrets
                key: OPENAI_ORG_ID
              
