apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-chart-agent
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: agent
  template:
    metadata:
      labels:
        app: agent
    spec:
      containers:
        - name: agent
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          ports:
            - containerPort: {{ .Values.service.containerPort }}
