apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: dodgy-service-alerts
  labels:
    release: {{ .Release.Name }} # Must match Prometheus instance label
  namespace: monitoring
spec:
  groups:
  - name: dodgy-service.rules
    rules:
    - alert: PodHighMemoryUsage
      expr: sum by (pod) (app_memory_usage) > 800
      for: 10s
      labels:
        severity: severe
        namespace: monitoring
      annotations:
        summary: "High memory usage on pod {{ `{{ $labels.pod }}` }}"
        description: "Pod {{ `{{ $labels.pod }}` }} has memory usage above 800 MB for over 10s."
