apiVersion: v1
kind: Service
metadata:
  name: agent-chart-agent-ui-service
spec:
  selector:
    app: agent-ui
  ports:
    - name: ui-exposed-http
      port: 80
      targetPort: ui-http
    - name: api-exposed-http
      port: 8000
      targetPort: api-http
