apiVersion: v2
name: agent-chart
description: A chart that spins up an SRE agent along with the prometheus monitoring stack

type: application

version: 0.1.0

appVersion: "1.16.0"

dependencies:
  - name: kube-prometheus-stack
    version: "69.0.0"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: monitoring-stack.enabled # Only uses this dependency if prometheus.enabled is true in values.yaml
