monitoring-stack:
  enabled: true

kube-prometheus-stack:
  alertmanager:
    enabled: true
    alertmanagerSpec:
      replicas: 1
      # Make sure it can see your CR
      alertmanagerConfigSelector:
        matchLabels:
          app.kubernetes.io/name: custom-alertmanager
      alertmanagerConfigNamespaceSelector: {}

replicaCount: 1

image:
  repository: agent-container
  # This sets the pull policy for images.
  pullPolicy: Never
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

service:
  type: ClusterIP
  containerPort: 8080

# Not using yet - for future anticipation
resources:
  limits:
    cpu: "500m"
    memory: "256Mi"
  requests:
    cpu: "250m"
    memory: "128Mi"
